server:
  port: 8080
  error:
    whitelabel:
      enabled: false

logging:
  level:
    root: "warn"
    com.kt.v1: "debug"
    org.springframework.web: "debug"
    org.hibernate: "info"
  file:
    name: service.log
    path: ./logs
  logback:
    rollingpolicy:
      max-history: 30
  register-shutdown-hook: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/winspec
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    show-sql: true
    open-in-view: false

  cache:
    type: redis
    cache-names: "ca1, ca2"

