server:
  port: 8080
  error:
    whitelabel:
      enabled: false

logging:
  level:
    web: debug

spring:
  profiles:
    active: dev
  application:
    name: kt-demo
  config:
    import: optional:configserver:http://127.0.0.1:8888
