server:
  port: 8080
  error:
    whitelabel:
      enabled: false

logging:
  level:
    web: debug


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/winspec
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    show-sql: true
  redis:
    primary:
      host: 127.0.0.1
      port: 6379
    reader:
      host: 127.0.0.1
      port: 6379
    database: 10
    lettuce:
      pool:
        max-idle: 100
        max-active: 50

